name: secure_mark
description: SecureMark - A professional application to secure documents with watermarks for safe sharing.
publish_to: 'none'
version: 1.5.1+16

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  pdf: ^3.10.6
  printing: ^5.14.3
  desktop_drop: ^0.7.0
  file_selector: ^1.1.0
  file_picker: ^10.3.10
  image_picker: ^1.1.2
  cunning_document_scanner: ^1.1.0
  image: ^4.1.7
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  pub_semver: ^2.1.5
  share_plus: ^12.0.1
  google_fonts: ^8.0.2
  http: ^1.2.1
  package_info_plus: ^8.0.0
  shared_preferences: ^2.3.2
  syncfusion_flutter_pdf: ^33.1.44
  url_launcher: ^6.3.1
  qr_flutter: ^4.1.0
  qr: ^3.0.1
  encrypt: ^5.0.3
  crypto: ^3.0.6
  archive: ^4.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.5.0
  flutter_launcher_icons: ^0.14.3
  test: ^1.19.0

flutter:
  uses-material-design: true
  generate: true
  
  # Custom fonts
  fonts:
    - family: LiberationMono
      fonts:
        - asset: assets/fonts/LiberationMono-Regular.ttf
    - family: LiberationSerif
      fonts:
        - asset: assets/fonts/LiberationSerif-Regular.ttf
    - family: Vera
      fonts:
        - asset: assets/fonts/Vera.ttf

  shaders:
    - shaders/watermark.frag

  assets:
    - images/guide/
    - assets/icon/
    - web/icons/

flutter_launcher_icons:
  android: true
  ios: true
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
  macos:
    generate: true
    image_path: "assets/icon/app_icon.png"
  linux: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
