name: secure_mark
description: SecureMark - A professional application to secure documents with watermarks for safe sharing.
publish_to: 'none'
version: 1.0.11+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  pdf: ^3.10.6
  printing: ^5.14.3
  desktop_drop: ^0.7.0
  file_selector: ^1.1.0
  image: ^4.1.7
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  google_fonts: ^8.0.2
  package_info_plus: ^8.0.0
  syncfusion_flutter_pdf: ^33.1.44
  flutter_foreground_task: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  generate: true
  
  # Custom fonts
  fonts:
    - family: CustomRoboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: CustomOpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Charis
      fonts:
        - asset: assets/fonts/Charis-Regular.ttf
        - asset: assets/fonts/Charis-Bold.ttf
          weight: 700
    - family: LiberationMono
      fonts:
        - asset: assets/fonts/LiberationMono-Regular.ttf
        - asset: assets/fonts/LiberationMono-Bold.ttf
          weight: 700
    - family: LiberationSerif
      fonts:
        - asset: assets/fonts/LiberationSerif-Regular.ttf
        - asset: assets/fonts/LiberationSerif-Bold.ttf
          weight: 700
    - family: Vera
      fonts:
        - asset: assets/fonts/Vera.ttf
        - asset: assets/fonts/VeraBd.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
  macos:
    generate: true
    image_path: "assets/icon/app_icon.png"
  linux: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
